### ISSUE TITLE
Add prefix of XSD types in TD example 

### ISSUE THREAD

**Issue by sebastiankb** [OPCFoundation/UA-EdgeTranslator#22]
In the TD example after Table 5, there is a prefix missing of the type value:

`"modbus:type": "float"`

Change to 

`"modbus:type": "xsd:float"`

Also see

https://w3c.github.io/wot-binding-templates/bindings/protocols/modbus/index.html#payloaddatatype

**Comment by barnstee** [comment]
Fixed with https://github.com/OPCFoundation/UA-EdgeTranslator/commit/c95d93ba53238855608ca46fc6124b10fc873d22
