### ISSUE TITLE
change prefix of modbus-based terms in TD examples

### ISSUE THREAD

**Issue by sebastiankb** [OPCFoundation/UA-EdgeTranslator#23]
The TD samples uses "modbus:" as prefix.  Usually it doesn't matter but for better readability and comparing to the [WoT Modbus Binding document ](https://w3c.github.io/wot-binding-templates/bindings/protocols/modbus/index.html#form-terms) it would be better to use "modv:" prefix.

E.g. 

`"modbus:pollingTime": 2000`

should be

`"modv:pollingTime": 2000`

**Comment by barnstee** [comment]
Fixed with https://github.com/OPCFoundation/UA-EdgeTranslator/commit/e368d46b5ce5c857b61705c618995fe66c80e01c.
