### ISSUE TITLE
Camel case of entity values

### ISSUE THREAD

**Issue by sebastiankb** [OPCFoundation/UA-EdgeTranslator#24]
The values of the `entity` modbus term follow camel case style (also see https://w3c.github.io/wot-binding-templates/bindings/protocols/modbus/index.html#entity).

Please change 

`"modbus:entity": "holdingregister",`

to 

`"modbus:entity": "HoldingRegister",`

**Comment by barnstee** [comment]
Fixed with https://github.com/OPCFoundation/UA-EdgeTranslator/commit/33dfc57d153f1b2c5f15ba129f53748671fad37d
