### ISSUE TITLE
Use the latest TD version in the context file

### ISSUE THREAD

**Issue by sebastiankb** [OPCFoundation/UA-EdgeTranslator#25]
The TD sample uses the TD 1.0 context version, however, TD 1.1 was already release.

Please change:

`https://www.w3.org/2019/wot/td/v1 `

to

`https://www.w3.org/2022/wot/td/v1.1`

**Comment by barnstee** [comment]
Fixed with https://github.com/OPCFoundation/UA-EdgeTranslator/commit/62b19e43ff87f2dce93c7628402faf7a248e4f7c
