### ISSUE TITLE
Update the context content in the TD sample

### ISSUE THREAD

**Issue by sebastiankb** [OPCFoundation/UA-EdgeTranslator#27]
The context file should be updated from
```
"@context": [
    "https://www.w3.org/2019/wot/td/v1",
    http://opcfoundation.org/UA/PNEM/
  ]
```

to

```
"@context": [
    "https://www.w3.org/2022/wot/td/v1.1",
     {
            "opcua": "http://opcfoundation.org/UA/PNEM/"
        },
  ]
```

Also see #25

**Comment by sebastiankb** [comment]
Btw: the namespace  http://opcfoundation.org/UA/PNEM/ is not existing. Is this the task of the new WoT OPC UA Binding WG?

**Comment by barnstee** [comment]
The namespace is a URI, not a URL :-)

**Comment by barnstee** [comment]
Fixed in https://github.com/OPCFoundation/UA-EdgeTranslator/commit/d0785a7697e338a6b936a61e5027b92be288d0c3.
