### ISSUE TITLE
Explanation of use

### ISSUE THREAD

**Issue by alexmc1510** [OPCFoundation/UA-EdgeTranslator#7]
Hello,

Would it be possible to have a brief explanation or example about how to use it? I am trying to use the sample files but I don't have a clear idea how it works. Is the software generating a OPC UA server? Is a tag mapper? How to create my own TD? The Readme focus on installation but the functional aspect is not clearly explained. If I manage to understand it a bit I don't mind to contribute with a better explanation.

Thanks in advance

**Comment by barnstee** [comment]
Hey @alexmc1510 , yes, it effectively is a tag mapper with a built-in OPC UA server. How to create TDs is already documented: "Thing descriptions can be easily edited using the [Eclipse Foundation's edi{TD}or](https://eclipse.github.io/editdor/)." To run UA-EdgeTranslator, you need a Docker-enabled PC. Feel free to make a readme contribution.
